### PR TITLE
bug - normalize end line in procfile

### LINKED ISSUE #1764: Tsuru do not support Procfile with end-line CRLF
I wrote a Procfile on windows and I did the deploy. I noticed that Tsuru does not support CRLF and does not tell the reason for the error

### PR DESCRIPTION
**Pull request by guiferpa**
fix [#1764](https://github.com/tsuru/tsuru/issues/1764)

### CODE REVIEW

File: tasks.go [hunk 1]
```diff
@@ -125,24 +125,31 @@ func buildHooks(yamlData TsuruYaml, envs []bind.EnvVar) error {
...
-	f, err := filesystem().Open(procfilePath)
+func readProcfile(path string) (string, error) {
+	CR := byte(13)
+	f, err := filesystem().Open(fmt.Sprintf("%v/Procfile", path))
 	if err != nil {
 		return "", err
 	}
 	defer f.Close()
 	procfile, err := ioutil.ReadAll(f)
+	procfile = append(procfile, CR)
```
Comment (cezarsa) [inline tasks.go]: Wouldn't it be easier here to simply call `procfile = bytes.Replace(procfile, []byte("\r\n"), []byte("\n"), -1)` instead of manually iterating on each byte? Do you see any problems with this approach?

**Review by cezarsa — CHANGES_REQUESTED** [review]
Sorry for taking so long to notice this PR.

File: tasks.go (hunk 1 above)
Comment (guiferpa) [reply tasks.go]: No problem

Comment (guiferpa) [reply tasks.go]: :up:

File: tasks.go [hunk 2]
```diff
@@ -125,24 +126,20 @@ func buildHooks(yamlData TsuruYaml, envs []bind.EnvVar) error {
...
-	procfilePath := fmt.Sprintf("%s/%s", defaultWorkingDir, "Procfile")
-	f, err := filesystem().Open(procfilePath)
+func readProcfile(path string) (string, error) {
+	f, err := filesystem().Open(fmt.Sprintf("%v/Procfile", path))
 	if err != nil {
 		return "", err
 	}
 	defer f.Close()
 	procfile, err := ioutil.ReadAll(f)
-	if err != nil {
```
Comment (cezarsa) [inline tasks.go]: We should not remove the error handling code here.

**Review by cezarsa — CHANGES_REQUESTED** [review]

File: tasks.go (hunk 2 above)
Comment (guiferpa) [reply tasks.go]: :up:

**Comment by cezarsa** [comment]
Thanks a lot!

**Comment by guiferpa** [comment]
:smile:
